defmodule ReportServer.Reports.TeacherStatus do
  alias ReportServer.PortalDbs
  alias ReportServer.Reports.Report

  def new() do
    %Report{
      slug: "teacher-status",
      title: "Teacher Status",
      subtitle: "Teacher status report",
      run: &run/1
    }
  end

  # real query - rename when Boris can connect to db
  def _run(_filters) do
    dev_query_portal = "learn.concord.org"
    dev_query = """
    select
      concat(u.first_name, ' ', u.last_name) as teacher_name,
      u.email as teacher_email,
      trim(ea.name) as activity_name,
      pc.name as class_name,
        date(po.created_at) as date_assigned,
        (select count(*) from portal_student_clazzes psc where psc.clazz_id = pc.id) as num_students_in_class,
        'TBD' as num_students_started,
        'TBD' as date_of_first_use,
        'TBD' as date_of_last_use
    from
      users u
    left join portal_teachers pt on (pt.user_id = u.id)
    left join portal_teacher_clazzes ptc on (ptc.teacher_id = pt.id)
    left join portal_clazzes pc on (pc.id = ptc.clazz_id)
    left join portal_offerings po on (po.clazz_id = pc.id)
    left join external_activities ea on (po.runnable_id = ea.id)
    where
      email = 'doug@zoopdoop.com'
    order by
      u.first_name, trim(ea.name)

    """

    PortalDbs.query(dev_query_portal, dev_query)
  end

  # for dev while Boris can't connect to db - this is the result of running IO.inspect(run([]), limit: :infinity)
  def run(_filters) do
    {:ok, %MyXQL.Result{
      columns: ["teacher_name", "teacher_email", "activity_name", "class_name",
       "date_assigned", "num_students_in_class", "num_students_started",
       "date_of_first_use", "date_of_last_use"],
      connection_id: 3679951,
      last_insert_id: nil,
      num_rows: 73,
      rows: [
        ["Doug Martin", "doug@zoopdoop.com",
         "(DEV!) Teaching Teamwork - Three Resistors Field Test",
         "Doug's Test Class", ~D[2018-01-09], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "(DEV!) Teaching Teamwork - Three Resistors Field Test (NOT SOLO)",
         "Doug's Test Class", ~D[2018-05-22], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "(DEV) Adder", "Doug's Test Class",
         ~D[2018-06-20], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "(Dev) breadboard",
         "Doug's Test Class", ~D[2018-06-20], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "(NEW SPREADSHEET) Draft Version Problem 2.2 – Hats Off to the Wumps: Changing a Figure’s Size and Location",
         "Demo Class", ~D[2017-11-09], 4, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "(NEW SPREADSHEET) Draft Version Problem 2.2 – Hats Off to the Wumps: Changing a Figure’s Size and Location",
         "Debug Class", ~D[2017-11-09], 1, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "1. Exploring a Model (DEBUG COPY)",
         "Doug's Test Class", ~D[2022-11-01], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "1.1 Your Beach - HI (2022 -2023)",
         "Doug's Test Class", ~D[2022-08-17], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "10-16-2017 Rules Off",
         "Doug's Test Class", ~D[2017-10-16], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "10-16-2017 Rules On",
         "Doug's Test Class", ~D[2017-10-16], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Another production attachment test",
         "Doug's Test Class", ~D[2022-07-15], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Comparing and Scaling Problem 1.2 Mixing Juice: Comparing Ratios",
         "Doug's Test Class", ~D[2018-01-25], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Copy of 2: Spring and Mass Experiment (InquirySpace)",
         "Doug's Test Class", ~D[2016-03-29], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Copy of 7: Hands-On Experiment with Dual Sensor Data Collection (InquirySpace)",
         "Doug's Test Class", ~D[2016-03-25], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Copy of Lesson 3: Alaska - Building Rules", "Doug's Test Class",
         ~D[2019-10-22], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Copy of Running out of breath",
         "Doug's Test Class", ~D[2019-04-26], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Doug's MYW Test", "Doug's Test Class",
         ~D[2024-06-17], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Draft - Stretching and Shrinking 2.2",
         "Doug's Test Class", ~D[2017-10-12], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Feb 2, 2018 Demo",
         "Doug's Test Class", ~D[2018-02-08], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Geniventure",
         "Atlas 4 Migration Test", ~D[2021-04-29], 2, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Geniventure", "Doug's Test Class",
         ~D[2020-12-09], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "How can I design a vehicle to be safer for a passenger during a collision? (Fall 2018)",
         "Doug's Test Class", ~D[2022-07-25], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Investigation 1 - Why does fresh pineapple prevent jello from solidifying? AB",
         "Doug's Test Class", ~D[2019-05-20], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Lesson 1: Alaska - Making an Initial Prediction", "Doug's Test Class",
         ~D[2019-01-23], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Lesson 1: Alaska Mainland - Making an Initial Prediction",
         "Doug's Test Class", ~D[2020-01-10], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Lesson 1: Discover Your Local Watershed", "Doug's Test Class",
         ~D[2021-03-03], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Lesson 2: Alaska - Visualizing Data",
         "Doug's Test Class", ~D[2019-01-23], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Lesson 3: New England - Building Rules", "Doug's Test Class",
         ~D[2019-02-27], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Linked Interactive UI Integration: AP", "Doug's Test Class",
         ~D[2022-01-14], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Linked Interactive UI Integration: Lara", "Doug's Test Class",
         ~D[2022-01-14], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Live test activity",
         "Doug's Test Class", ~D[2018-02-08], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Localhost Collabspace Test",
         "Doug's Test Class", ~D[2018-04-06], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "March 1st Demo", "Doug's Test Class",
         ~D[2018-03-01], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 1 Mathematical Reflections (Live Annotation)",
         "MSU Test Class", ~D[2018-04-30], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 1 Mathematical Reflections (Snapshot Annotation)",
         "MSU Test Class", ~D[2018-04-30], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 1.1 Walking Marathons: Finding and Using Rates",
         "Doug's Test Class", ~D[2018-02-22], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 1.1 Walking Marathons: Finding and Using Rates (Live Annotation)",
         "MSU Test Class", ~D[2018-04-29], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 1.1 Walking Marathons: Finding and Using Rates (Snapshot Annotation)",
         "MSU Test Class", ~D[2018-04-30], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 1.2 Walking Rates and Linear Relationships: Tables, Graphs, and Equations (Live Annotation)",
         "MSU Test Class", ~D[2018-04-30], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 1.2 Walking Rates and Linear Relationships: Tables, Graphs, and Equations (Snapshot Annotation)",
         "MSU Test Class", ~D[2018-04-30], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 1.3 Raising Money: Using Linear Relationships (Live Annotation)",
         "MSU Test Class", ~D[2018-04-30], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 1.3 Raising Money: Using Linear Relationships (Snapshot Annotation)",
         "MSU Test Class", ~D[2018-04-30], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 1.4 Using the Walkathon Money: Recognizing Linear Relationships (Live Annotation)",
         "MSU Test Class", ~D[2018-04-30], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 1.4 Using the Walkathon Money: Recognizing Linear Relationships (Snapshot Annotation)",
         "MSU Test Class", ~D[2018-04-30], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Moving Straight Ahead Problem 3.1: Mystery Pouches in the Kingdom of Montarek: Exploring Equality",
         "Doug's Test Class", ~D[2018-03-09], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "MSA 2.2 Comparing Cost Relationships",
         "Doug's Test Class", ~D[2021-05-10], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Mugwumps Demo",
         "Doug's Second Test Class", ~D[2017-09-27], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Mugwumps Demo", "Doug's Test Class",
         ~D[2017-09-27], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Mugwumps Demo 3", "Doug's Test Class",
         ~D[2017-10-13], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Mugwumps Localhost Test!",
         "Doug's Test Class", ~D[2017-10-19], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Offline Alaska 2021 - Lesson 1 - Making an Initial Prediction",
         "Doug's Test Class", ~D[2021-04-14], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Plate Tectonics Module",
         "Doug's Test Class", ~D[2021-01-19], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Running out of breath",
         "Doug's Test Class", ~D[2019-04-26], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "SageModeler Linked",
         "Doug's Test Class", ~D[2022-02-28], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Smoke Test 1", "Test PT #178456056",
         ~D[2022-11-18], 1, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "SS 1.2 Stretching a Figure: Comparing Similar Figures",
         "Doug's Test Class", ~D[2018-10-15], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "SS 2.2 Hats off to the Wumps: Changing a Figure's Size and Location",
         "Doug's Test Class", ~D[2018-10-16], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "SS 4.3 More Impostors",
         "Doug's Test Class", ~D[2018-10-16], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Stretching and Shrinking Problem 2.2 10/16 Demo", "MSU Test Class",
         ~D[2018-05-09], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Teaching Teamwork - Adder",
         "Doug's Test Class", ~D[2018-05-29], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Teaching Teamwork - Three Resistors Field Test", "Doug's Test Class",
         ~D[2018-01-05], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Test Bar Chart Interactive",
         "Doug's Test Class", ~D[2022-10-21], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Test CODAP Clear",
         "Doug's Test Class", ~D[2022-08-15], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Test Group 1", "Doug's Test Class",
         ~D[2017-10-13], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Test Open Response Audio Transcriptions", "Doug's Test Class",
         ~D[2024-05-21], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Test Production Attachments",
         "Doug's Test Class", ~D[2022-07-14], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Test Sage Reporting Crash",
         "Doug's Test Class", ~D[2022-10-17], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Test Single Migration",
         "Doug's Test Class", ~D[2022-07-25], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Test timeouts", "MSU Test Class",
         ~D[2018-05-17], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "Three-Resistor Activity",
         "Doug's Test Class", ~D[2018-10-24], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "TT One Page with Save State",
         "Doug's Second Test Class", ~D[2018-05-31], 3, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com", "TT One Page with Save State",
         "Doug's Test Class", ~D[2018-05-23], 10, "TBD", "TBD", "TBD"],
        ["Doug Martin", "doug@zoopdoop.com",
         "Why do I feel colder when I am wet than when I am dry? (v3)",
         "Doug's Test Class", ~D[2023-03-23], 10, "TBD", "TBD", "TBD"]
      ],
      num_warnings: 0
    }}
  end
end
