defmodule ReportServer.Demo do

  def raw_demo_csv() do
    """
    "student_id","user_id","student_name","username","school","class","class_id","permission_forms","teacher_user_ids","teacher_names","teacher_districts","teacher_states","teacher_emails","res_1_name","res_1_learner_id","res_1_remote_endpoint","res_1_resource_url","res_1_last_run","res_1_total_num_questions","res_1_total_num_answers","res_1_total_percent_complete","res_1_num_required_questions","res_1_num_required_answers","res_1_managed_interactive_5849_text","res_1_managed_interactive_5849_url"
    "Correct answer",,,,,,,,,,,,,,,,,,,,,,,,
    "Prompt",,,,,,,,,,,,,,,,,,,,,,,"1: (no prompt)","1: (no prompt)"
    "6","27","Test Student One","tstudentone","Concord Consortium","Test Class","6","[]","14","Doug Martin","","","dmartin@concord.org","Test Open Response url in details report","264","https://learn.portal.staging.concord.org/dataservice/external_activity_data/36bd3464-f63a-4d0c-a7a1-aefebba85d02","https://activity-player.concord.org/branch/master/?activity=https%3A%2F%2Fauthoring.lara.staging.concord.org%2Fapi%2Fv1%2Factivities%2F598.json","2024-03-13T13:26:49.000Z","1","1","100.0","0","0","""this is my text answer""","https://portal-report.concord.org/branch/master/index.html?auth-domain=https%3A%2F%2Flearn-report.portal.staging.concord.org&firebase-app=report-service-dev&sourceKey=authoring.lara.staging.concord.org&iframeQuestionId=managed_interactive_5849&class=https%3A%2F%2Flearn-report.portal.staging.concord.org%2Fapi%2Fv1%2Fclasses%2F6&offering=https%3A%2F%2Flearn-report.portal.staging.concord.org%2Fapi%2Fv1%2Fofferings%2F328&studentId=27&answersSourceKey=activity-player.concord.org"
    "87","199","Test Student Two","tstudenttwo","Concord Consortium","Test Class","6","[]","14","Doug Martin","","","dmartin@concord.org","Test Open Response url in details report","265","https://learn.portal.staging.concord.org/dataservice/external_activity_data/cdbc6166-278b-41b1-aa9c-e4512f26082f","https://activity-player.concord.org/branch/master/?activity=https%3A%2F%2Fauthoring.lara.staging.concord.org%2Fapi%2Fv1%2Factivities%2F598.json","2024-03-13T17:33:40.000Z","1","0","0.0","0","0",,"https://portal-report.concord.org/branch/master/index.html?auth-domain=https%3A%2F%2Flearn-report.portal.staging.concord.org&firebase-app=report-service-dev&sourceKey=authoring.lara.staging.concord.org&iframeQuestionId=managed_interactive_5849&class=https%3A%2F%2Flearn-report.portal.staging.concord.org%2Fapi%2Fv1%2Fclasses%2F6&offering=https%3A%2F%2Flearn-report.portal.staging.concord.org%2Fapi%2Fv1%2Fofferings%2F328&studentId=199&answersSourceKey=activity-player.concord.org"
    "88","204","Test Student Three","tthree","Concord Consortium","Test Class","6","[]","14","Doug Martin","","","dmartin@concord.org","Test Open Response url in details report","288","https://learn.portal.staging.concord.org/dataservice/external_activity_data/9609c6b9-1fd9-4f56-976b-6e7cd4ab54b6","https://activity-player.concord.org/branch/master/?activity=https%3A%2F%2Fauthoring.lara.staging.concord.org%2Fapi%2Fv1%2Factivities%2F598.json","2024-03-31T13:08:29.000Z","1","1","100.0","0","0","","https://portal-report.concord.org/branch/master/index.html?auth-domain=https%3A%2F%2Flearn-report.portal.staging.concord.org&firebase-app=report-service-dev&sourceKey=authoring.lara.staging.concord.org&iframeQuestionId=managed_interactive_5849&class=https%3A%2F%2Flearn-report.portal.staging.concord.org%2Fapi%2Fv1%2Fclasses%2F6&offering=https%3A%2F%2Flearn-report.portal.staging.concord.org%2Fapi%2Fv1%2Fofferings%2F328&studentId=204&answersSourceKey=activity-player.concord.org"
    """
  end

end
