# this is just for testing releases locally, not for deployment of releases!
name: report-server
services:
  app:
    image: concordconsortium/report-server
    build: .
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - PHX_HOST=localhost
      - SECRET_KEY_BASE="${SECRET_KEY_BASE:-FAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKE}"
      - SERVER_ACCESS_KEY_ID="${SERVER_ACCESS_KEY_ID:-}"
      - SERVER_SECRET_ACCESS_KEY="${SERVER_SECRET_ACCESS_KEY:-}"
      - REPORT_SERVICE_TOKEN="${REPORT_SERVICE_TOKEN:-}"

