# This is only used for local development to run a MySql instance that mirrors the RDS instance.
# The server should be run directly on your development machine, see the README for details.
name: report-server-dev-db
services:
  db:
    image: mysql:8.0.39
    ports:
      - 3406:3306 # expose mysql to the world
    environment:
      MYSQL_ROOT_PASSWORD: xyzzy
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      # use a named volume here so the database is preserved after a down and up
      - mysql:/var/lib/mysql
volumes:
  mysql: